### ISSUE TITLE
libgnustl_shared.so origin

### ISSUE THREAD

**Issue by JEMoralesD** [AxelNennker/DroidLibIndy#2]
Where does this file comes from? I have built the libraries forllowing these [instructions](https://github.com/hyperledger/indy-sdk/blob/master/docs/build-guides/android-build.md)
and I am only getting a libindy.so libindy.a and libindy_shared.so  files. When I try to run the project however I am getting an error

```
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libgnustl_shared.so" not found
 at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
 at java.lang.System.loadLibrary(System.java:1657)
```

**Comment by AxelNennker** [comment]
It is part of the NDK. At that time I used NDK 16.
```
ignisvulpis@namenlos:~$ cd Android/
ignisvulpis@namenlos:~/Android$ find . -name libgnustl_shared.so
./NDK/x86/i686-linux-android/lib/libgnustl_shared.so
./NDK/arm/arm-linux-androideabi/lib/thumb/libgnustl_shared.so
./NDK/arm/arm-linux-androideabi/lib/libgnustl_shared.so
./NDK/arm/arm-linux-androideabi/lib/armv7-a/thumb/libgnustl_shared.so
./NDK/arm/arm-linux-androideabi/lib/armv7-a/libgnustl_shared.so
./NDK/arm64/aarch64-linux-android/lib/libgnustl_shared.so
ignisvulpis@namenlos:~/Android$ 
```
